import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css'

import { Poppins } from 'next/font/google'
import Navbar from "./navbar/navbar";

const PoppinsFont = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['400', '700' ,'500' , '600']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`md:pt-[60px] bg-[#E7F1E9] pt-16   font-poppins ${PoppinsFont.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
